version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing requirements"
      - pip install --upgrade --force-reinstall . awscli
      - pip install -r $CODEBUILD_SRC_DIR/pipelines/requirements.txt
  
  pre_build:
    commands:
      - echo "List source files"
      - echo "Get pipeline name"
      - export PIPELINE_NAME=${CODEBUILD_INITIATOR#codepipeline/}
      - echo $PIPELINE_NAME    
  
  build:
    commands:
      - echo Build started on `date`
      - cd $CODEBUILD_SRC_DIR
      - pylint pipelines --files-output=y --output-format=text > testresult.txt
     #- python -m flake8 pipelines --output-file=lint-testresults.xml --format junit-xml

  
  post_build:
    commands:
      - echo Lint test completed on `date`
 
